### ISSUE TITLE
Your IDE??

### ISSUE THREAD

**Issue by StanleyDelva** [AntiElephantMine/Running#1]
What IDE do you use? I've been trying to put all of your files together and open it open them in Code::Blocks but can't seem to do so... If you use Code::Blocks, could you add the ".cbp" file?

**Comment by StefanCardnell** [comment]
Hi, I use Code::Blocks too. I hope you're only trying to open the .cpp or .h Source files in your IDE. The gitignore/gitattributes or the exectuable won't open in CodeBlocks.

**Comment by StanleyDelva** [comment]
Yeah, I know about the git files. I was just having problems grouping all your files into a single project... I'll have to that later. Thanks

**Comment by StefanCardnell** [comment]
Hmm that's odd, not sure what the issue could be. At the very least you could try copy/pasting the code lines in to your own files (making sure to keep the same file names). Sorry about that.

**Comment by StefanCardnell** [comment]
What's the exact problem? What happens when you right click your project, click Add Files and select all three Source files?

**Comment by StanleyDelva** [comment]
Ok, I made copy of your project like you suggested (Good idea btw)... When compiling your project I encountered the error  " 'runtime_error' was not declared in this scope" many many times... I'm sorry to say I can't help with that :( BUT I can say that u need to put in return types in some of the string functions in "Record.cpp" I'm sorry for not doing much but I'm still learning

**Comment by StefanCardnell** [comment]
I think the problem here is that I haven't included the `exception` and `stdexcept` headers, but they get included by another header on my system - but maybe not on yours (I'd find that very odd though, classes like `iostream` need `runtime_error`, are you also making sure to include `using namespace std;`?)

Try putting 

`#include <exception>`
`#include <stdexcept>`

at the top of `Record.cpp` and `Running.cpp`. I'm still new to sharing my code with others, so I still have to get to grips with portability. I've updated the source files to include this. 

As for the return types, could you copy-paste what function you think is wrong?

**Comment by StanleyDelva** [comment]
The two `#includes` worked like a charm. I did include `using namespace std;` earlier, though. As for the return types, I sent a pull request so check that out.

**Comment by StanleyDelva** [comment]
Hold up nevermind I did something different.. I'll send the pull request ASAP
